export interface IDelegationDetails {
  crabd_newcolumn?: number; // Primary key (autogenerated number)
  crabd_applicationid: string; // Foreign key to Application
  createdon: Date; // Date when the record was created
  crabd_delegateto: string; // User to whom the delegation is assigned
  crabd_delegationid?: number; // Foreign key to Delegation
}

export interface IDelegation {
  crabd_delegationfrom?: number; // Primary key (autogenerated number)
  crabd_enddate: Date; // End date of the delegation
  crabd_startdate: Date;
  crabd_applytoexistingtask:boolean; // Start date of the delegation
  // createdby: string; // User who created the delegation (logged in user)
}
